version: "3"

services:

  frontend:
    build:
        context: ../brewlog-ui/
        dockerfile: Dockerfile
    image: brewlog-ui:latest
    depends_on:
      - backend
    links:
      - backend
    ports:
      - "4200:80"

  backend:
    build:
          context: .
          args:
            BUILD_VERSION: 0.0.1-SNAPSHOT
          dockerfile: Dockerfile
    image: brewlog:latest
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mysql:latest
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_DATABASE=brews
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=springboot
      - MYSQL_PASSWORD=springboot
#    volumes:
#      - /home/docker/data/MYSQL/data:/var/lib/mysql
#      - /home/docker/data/MYSQL/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

#volumes:
#
#  d/data/MYSQL/data:
#    driver: "local"
#
#  d/data/MYSQL/init:
#    driver: "local"
