version: "3"

services:

  frontend:
    build:
      context: ./brew-ui/
      dockerfile: Dockerfile
    image: brewlog-ui:latest
    depends_on:
      - backend
    ports:
      - 4200:80

  backend:
    build:
      context: ./brew-server
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: 0.0.1-SNAPSHOT
        dockerfile: Dockerfile
    image: brewlog:latest
    depends_on:
      - db
    ports:
      - 8082:8080

  db:
    build:
      context: ./brew-db
      dockerfile: Dockerfile
    # volumes:
    #  - db-data:/var/lib/postgresql/data/
    image: brewlog-db:latest
    ports:
     - 5432:5432

volumes:
  db-data: