server:
  port: 8080

# Application Settings and Datasource
spring:
  application:
    name: brewlog
  datasource:
    url: jdbc:mysql://10.1.1.79:3306/brews
    username: springboot
    password: springboot

  #JPA-Hibernate
  jpa:
    hibernate:
      ddl-auto: validate

      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    database: mysql

brews:
  app:
    jwtSecret: jwtSecretKeyThatNoOneMustKnow
    jwtExpiration: 86400