server:
  port: 8080

#Datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/brews
    username: springboot
    password: springboot

#JPA-Hibernate
  jpa:
    hibernate:
      ddl-auto: update

      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database: mysql

