server:
  port: 8080

# Application Settings and Datasource
spring:
  application:
    name: brewlog
  datasource:
    url: jdbc:postgresql://10.1.1.79:5432/brewdb
    username: springboot
    password: springboot

  # Flyway
  flyway:
    baseline-on-migrate: false

  #JPA-Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

springdoc:
#  api-docs:
#    path: /brewlog-openapi
  packagesToScan: brews.app.presentation.rest.controllers,brews.app.presentation.rest.controllers.exceptionhandler


#  pathsToMatch: /api/brews, /api/recipes, /api/measurement, /api/user, /api/auth

brews:
  app:
    jwtSecret: jwtSecretKeyThatNoOneMustKnow
    jwtExpiration: 86400