
spring:
  datasource:
    url: jdbc:postgresql://10.1.1.79:5432/brewdb
    username: springboot
    password: springboot

brews:
  app:
    jwtSecret: jwtSecretKeyThatNoOneMustKnow
    jwtExpiration: 86400
    cors:
      origins: http://localhost:4200/*,http://192.168.99.100:4200