
spring:
   flyway:
     locations: classpath:db/migration-test

   datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

   jpa:
     show-sql: true
     database: h2
     properties:
       hibernate:
         dialect: org.hibernate.dialect.H2Dialect

brews:
  app:
    jwtSecret: jwtSecretKeyThatNoOneMustKnow
    jwtExpiration: 86400