server:
  port: 8080

# Application Settings and Datasource
spring:
  application:
    name: brewlog

  # Flyway
  flyway:
    baseline-on-migrate: false

  #JPA-Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

springdoc:
  packagesToScan: brews.app.presentation.rest.controllers,brews.app.presentation.rest.controllers.exceptionhandler
