apiVersion: v1
kind: Service
metadata:
  name: brew-backend
  labels:
    app: brew-backend
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: brew-backend
    tier: backend